<?php
/**
 * Created by PhpStorm.
 * User: PHP
 * Date: 2020/5/21
 * Time: 10:05
 */

namespace app\admin\controller;

use app\admin\model\Admin as AdminModel;
use function PHPSTORM_META\type;
use think\Log;

class Administrators extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model=new AdminModel();
    }

    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

    public function add(){
        if(request()->isPost()){
            $data=request()->param();
            $this->saved($data);
        }
        return view();
    }

    public function edit(){
        if(request()->isPost()){
            $data=request()->param();
            $this->saved($data);
        }
        return view();
    }

    public function lists(){

    }

    public function saved($data,$interfaseNumber=70001){
        if(!empty($data)){
            switch ($data){
                case $data["type"]=="add":
                    unset($data["type"]);
                    try{
                        $this->model->save($data);
                    }catch (\Exception $e){
                        \think\Log::record("添加:".$e->getMessage());
                     return adminShow(config("code.fail"),config("message.fail"),$data,$interfaseNumber);
                    }
                    return adminShow(config("code.success"),config("message.success"),$data,$interfaseNumber);
                    break;
                case $data["type"]=="edit":
                    unset($data["type"]);
                    try{
                        $this->model->save($data);
                    }catch (\Exception $e){
                        \think\Log::record("修改:".$e->getMessage());
                        return adminShow(config("code.fail"),config("message.fail"),$data,$interfaseNumber);

                    }
                    return adminShow(config("code.success"),config("message.success"),$data,$interfaseNumber);
                    break;
            }
        }
        return adminShow(config("code.fail"),config("message.null"),$data,$interfaseNumber);
    }

    public function delete(){

    }


}