<?php
/**
 * Created by PhpStorm.
 * User: PHP
 * Date: 2020/5/6
 * Time: 10:48
 */
namespace app\admin\controller;
use app\admin\BaseController;

class Base extends BaseController
{
    public $adminUser;//管理员名称
    public $adminType;//管理员身份
    public $adminId;//管理员id
    public $model;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(empty(session(config("session.admin_username")))){
            redirect("anns")->send();
        }

    }

    public function index(){
        return view();
    }





}