<?php
/**
 * Created by PhpStorm.
 * User: PHP
 * Date: 2020/5/19
 * Time: 16:15
 */

namespace app\admin\controller;


class Menu extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

   public function index()
   {
       return parent::index(); // TODO: Change the autogenerated stub
   }

   public function add(){
        if(request()->isPost()){
            $data=request()->param();
            $this->save($data);
        }
        return view();
   }

   public function edit(){
       if(request()->isPost()){
           $data=request()->param();
           $this->save($data);
       }
        return view();
   }

   public function lists(){

   }

   public function save($data){
        if(!empty($data)){
            switch ($data){


            }
        }
   }

   public function delete(){

   }

}