<?php
/**
 * Created by PhpStorm.
 * User: PHP
 * Date: 2020/6/1
 * Time: 17:24
 */

namespace app\admin\controller;


class Role extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function lists(){

    }

}